var app = angular.module('adm',[ 'ui.router',
                                'ngCookies',
                                'ngAnimate',
                                'ui.mask',
                                'ui.bootstrap',
                                'ui.grid',
                                'ui.grid.selection',
                                'ui.grid.pagination',
                                'ui.grid.autoResize',
                                'ui-notification',
                                'ui.select',
                                'ui.ace',
                                'ui.utils.masks',
                                'schemaForm',
                                'ngSanitize']);
